name: pratospilla
description: Vacation Rental app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  table_calendar: ^3.1.2
  intl: ^0.20.2
  http: ^1.2.0
  icalendar_parser: any
  googleapis: ^16.0.0
  googleapis_auth: ^2.0.0
  google_sign_in: ^7.2.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  firebase_core: ^4.5.0
  cloud_firestore: ^6.1.3
  firebase_storage: ^13.1.0
  image_picker: ^1.1.2
  firebase_auth: ^6.2.0
  url_launcher: ^6.3.2
  file_picker: ^10.3.10
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
